# Disable sudo to speed up the build.
sudo: false

# Set the build language to Python.
language: python

# Set the python version
python: 3.10.6

# Install the codecov pip dependency.
install:
  - pip install codecov

# Run the unit tests.
script:
  - coverage run --source=./demo_repo -m pytest

# Push the results back to codecov.
after_success:
  - codecov
